---
title: "Practice Survival PYQ"
author: "Ahmad Firdaus Mohamed"
date: "2024-01-22"
output: word_document
---

# Survival Analysis

# Load Library

```{r}
library(survival)
library(gtsummary)
library(survminer)
library(tidyverse)
library(broom)
library(lubridate)
library(haven)
library(dplyr)
library(corrplot)
library(mfp)
```

## Read Data

```{r}
stroke <- read_dta ("stroke_outcome.dta")
```

```{r}
summary(stroke)
```

```{r}
stroke <- stroke %>%
  mutate_if(is.labelled,~as_factor(.))
```

```{r}
summary(stroke)
```

```{r}
stroke <- stroke %>%
  mutate(dur=stroke$doa %--% stroke$dod) %>%
           mutate(dur=as.duration(dur)) %>%
  mutate(dur_days = dur/ddays (1))

```

```{r}
stroke <- stroke %>% 
  mutate(category=cut(stroke$sbp, c (0,140,160,300), label = c('normal', 'hpt1','hpt2')))
  
```

```{r}
KM1 <- survfit(Surv(time = dur_days, event == 'dead')~1, type= "kaplan-meier", data = stroke)
summary(KM1)
```

```{r}
plotKM <- ggsurvplot(KM1, conf.int = TRUE, surv.median.line = "hv", xlab="days") ##surv.median.line = "hv", xlab("Days"), ylab= "survival probability", break.time.by = 20, risk.table =T)
plotKM
```

```{r}
quantile (KM1, probs = c (0.25,0.50, 0.75))
```

```{r}
summary(KM1, times = c(10, 20, 30))
```

```{r}
KMlogrank <- survdiff(Surv(time = dur_days, event == "dead")~sex, data = stroke, rho = 0)
KMlogrank
```

```{r}
KMpeto <- survdiff(Surv(time = dur_days, event == "dead")~sex, data = stroke, rho = 1)
KMpeto
```

p\>0.05, hence there is no difference between survival probability of male and female

Efron Method

```{r}
cox1 <- coxph(Surv(time = dur_days, event == "dead")~sex + sbp + sex:sbp, data = stroke)
cox1
```

Breslow Method

```{r}
cox2 <- coxph(Surv(time = dur_days, event == "dead")~sex + sbp + dm2, data = stroke, method = 'breslow')
cox2
```
